import type { Metadata } from "next";
import GlobalStyle from "@/styles/globalStyle";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "파도 상점",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <GlobalStyle />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
