import type { Metadata } from "next";
import GlobalStyle from "@/styles/globalStyle";
import Header from "@/components/header";
import Footer from "@/components/footer";
import ScrollToTop from "./scrollToTop";
import StyledComponentsRegistry from "@/styles/registry";

export const metadata: Metadata = {
  title: "파도상점",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <StyledComponentsRegistry>
          <GlobalStyle />
          <ScrollToTop />
          <Header />
          {children}
          <Footer />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
